databases:
  - name: animetoon
    ipAllowList: []
    databaseName: animetoon
    user: animetoon
    plan: free
services:
  - type: web
    name: animetoon
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animetoon
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false